### ISSUE TITLE
DLSS 3.6.0

### ISSUE THREAD

**Issue by revanmj** [beeradmoore/dlss-archive#9]
There is new version - 3.6.0 from Naraka Bladepoint
https://www.techpowerup.com/download/nvidia-dlss-dll/

**Comment by beeradmoore** [comment]
Was on it earlier, but there is an issue with the dlss-archive builder tool. It seems to be generating different hash for builds that already existed. Both local and fresh remote seem to be giving odd numbers which means it's an issue with tool itself not the files themselves.

**Comment by beeradmoore** [comment]
Fixed. Who knew that creating a zip file one day can give you a diiffernet zip file the next day, I certainly didn't 😂

The fix is probably what it should have done in the beginning. It had always made sure it had ALL of the DLSS files from here by downloading them before continuing. In the past it would open those and re-create new DLSS zips and put them in the output directory.

The problem is it would download the zip, extract the single dll, and create a new zip wth that file. This should be an identical file (or so I thought), but the size was off by 1byte. Actual data in a diff was very off.

Updated the code to instead check the MD5 of the zip it downloaded and if it matches what we expect it will just ignore trying to re-process that file.
